name: sync-upstream

on:
  schedule:
    # every hours
    - cron: '0 * * * *'
  workflow_dispatch:
    branches:
      - 'master'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build env
        run: |
          bin/setup-build-env
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          bin/configure-git

      - name: Sync submodule
        run: bin/sync-submodule
      - name: Push changes
        run: bin/push-changes "Update upstream"

      - name: Exec po4a-updatepo
        run: |
          bin/exec-po4a-updatepo

      - name: Push changes
        run: bin/push-changes "Update .po files"

      - name: Update translation stats
        run: bin/update-translation-stats

      - name: Push changes
        run: bin/push-changes "Update translation stats"

      - name: Apply tmx
        run: bin/apply-tmx

      - name: Push changes
        run: bin/push-changes "Apply translation memory"

      - name: Machine translate
        run: bin/machine-translate
        env:
          TRANSLATOR_DEEPL_APIKEY: ${{ secrets.TRANSLATOR_DEEPL_APIKEY }}

      - name: Push changes
        run: bin/push-changes "Add machine translation"
